src/iquilar/bookings/urls.py
from django.conf.urls import url

from . import views

app_name = 'bookings'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.hotel_search_results, name='hotel_search_results'),
    url(r'^list/', views.hotel_city_results, name='hotel_city_results'),
    url(r'^property/([0-9]+)/$', views.hotel_details, name='hotel_details'),
    url(r'^check_availability/', views.check_availability, name='check_availability'),
    url(r'^reservation/([0-9]+)/$', views.successful_booking, name='successful_booking')
]

src/iquilar/iquilar/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('bookings/')),
    url(r'^bookings/', include('bookings.urls')),
    url(r'^admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/iquilar/bookings/models.py
import os
from django.db import models
from django.contrib.auth.models import User


def property_image_rename(instance, filename):
    path = "hotels/images/"
    if instance.id is not None:
        name = str(instance.id) + filename
    elif not Property.objects.last():
        name = str(1) + filename
    else:
        name = str(Property.objects.latest('id').pk + 1) + filename
    return os.path.join(path, name)


class City(models.Model):
    name = models.CharField(blank=False, null=False, max_length=100)
    picture = models.ImageField(blank=False, null=True, upload_to=property_image_rename)
    class Meta:
        verbose_name_plural = "cities"

    def __str__(self):
        return self.name


class Property(models.Model):
    name = models.CharField(blank=False, null=False, max_length=50, default="Property Name")
    description = models.TextField(blank=False, null=False, default="Awesome description", max_length=100)
    picture = models.ImageField(blank=False, null=True, upload_to=property_image_rename)
    max_pax = models.PositiveIntegerField(blank=False, null=False, default=1)
    daily_cost = models.FloatField(blank=False, null=False, default=0)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING, null=True, blank=False)
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name_plural = "properties"

    def __str__(self):
        return self.name


class Reservation(models.Model):
    reservation_date = models.DateField(blank=False, null=False, auto_now=True)
    total_amount = models.FloatField(blank=True, null=True)
    first_name = models.CharField(blank=True, null=True, max_length=50)
    last_name = models.CharField(blank=True, null=True, max_length=50)
    email = models.EmailField(blank=True, null=True, max_length=200)
    property = models.ForeignKey(Property, on_delete=models.PROTECT, blank=False, null=False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class ReservationDate(models.Model):
    date = models.DateField(blank=False, null=False)
    property = models.ForeignKey(Property, on_delete=models.PROTECT, blank=False, null=False)
    reservation = models.ForeignKey(Reservation, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.property.name

src/iquilar/bookings/views.py
from datetime import datetime

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.template import loader
from django.views import generic

from .models import City, Property, ReservationDate, Reservation


def index(request):
    cities = City.objects.all()
    context = {'cities': cities }
    return render(request, 'bookings/index.html', context)


def hotel_search_results(request):
    if request.method == 'GET':
        properties = Property.objects.all()
        context = {'properties': properties}
        return render(request, 'bookings/hotel-search-results.html', context)
    if request.method == 'POST':
        city = request.POST['city']
        pax = request.POST['pax']
        max_price = request.POST['max_price']
        properties = Property.objects.all()

        if not city.__eq__('None'):
            properties = properties.filter(city=city)

        if not pax.__eq__('None'):
            properties = properties.filter(max_pax__gte=pax)

        if max_price is not '':
            properties = properties.filter(daily_cost__lte=max_price)

        context = {'properties': properties}
        return render(request, 'bookings/hotel-search-results.html', context)

def hotel_city_results(request):
    if request.method == 'GET':
        properties = Property.objects.all()
        context = {'properties': properties}
        return render(request, 'bookings/hotel-hotel-list.html', context)
    if request.method == 'POST':
        city = request.POST['city']
        properties = Property.objects.all()

        if not city.__eq__('None'):
            properties = properties.filter(city=city)

        context = {'properties': properties}
        return render(request, 'bookings/hotel-list.html', context)


def hotel_details(request, property_id):
    try:
        requested_property = Property.objects.get(id=property_id)
    except Property.DoesNotExist:
        raise Http404("Not Found")
    return render(request, 'bookings/hotel-details.html', {'property': requested_property})


def check_availability(request):
    if request.method == 'POST':
        datetime_start_date = datetime.strptime(request.POST['start_date'], '%Y-%m-%d').date()
        datetime_end_date = datetime.strptime(request.POST['end_date'], '%Y-%m-%d').date()
        requested_property = Property.objects.get(id=request.POST['property_id'])
        reservation_dates = ReservationDate.objects.filter(property=requested_property.id)
        for reservation_date in reservation_dates:
            if reservation_date.reservation is not None:
                if datetime_start_date <= reservation_date.date <= datetime_end_date:
                    return render(request, 'bookings/no-availability.html')
        r = Reservation(
            reservation_date=datetime.now().date(),
            property=requested_property,
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            email=request.POST['email'])
        r.save()
        count = 0
        for reservation_date in reservation_dates:
            if datetime_start_date <= reservation_date.date <= datetime_end_date:
                reservation_date.reservation = r
                reservation_date.save()
                count = count + 1
        if count == 0:
            return render(request, 'bookings/no-availability.html')
        r.total_amount = r.property.daily_cost * r.property.reservationdate_set.filter(reservation=r).count()
        r.save()
        return redirect('bookings:successful_booking', r.id)


def successful_booking(request, reservation_id):
    try:
        requested_reservation = Reservation.objects.get(id=reservation_id)
    except Property.DoesNotExist:
        raise Http404("Not Found")
    return render(request, 'bookings/itinerary.html', {'reservation': requested_reservation})

src/iquilar/bookings/templates/base/base.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
	<title>iQuilar - {% block title %}Base{% endblock %}</title>

	<link rel="icon"
	      type="image/png"
	      href="{% static 'favicon.png' %}"/>

	<!-- Required meta tags -->
	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0-beta.2-dist/css/bootstrap.min.css' %}"/>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	        crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
	        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
	        crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
	        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
	        crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'animate-css/animate.css' %}"/>

	{% block styles %}{% endblock %}

</head>

<body>

<div id="content">
	{% block content %}{% endblock %}
</div>

{% block scripts %}{% endblock %}

</body>

</html>

src/iquilar/bookings/templates/base/footer.html
<footer class="footer">
	<div class="container">
		<span class="text-muted">
			Made by
			<a>Bernardo Chiletto</a> &
			<a>Mariano Fernandez</a>
		</span>
	</div>
</footer>

src/iquilar/bookings/templates/base/navbar.html
{% load static %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
	{% url 'bookings:index' as index %}
	<a class="navbar-brand" href="{{ index }}">
		<img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
		     alt="iquilar logo">
		iQuilar
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
	        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">

		</ul>
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link active" href="{{ index }}">Hotels <span class="sr-only">(current)</span></a>
			</li>
		</ul>
	</div>
</nav>

src/iquilar/bookings/templates/bookings/hotel-details.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../base/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-10 offset-md-1 pt-3 pb-3" style="background-color: #f5f5f5;">
				<section class="row tm-item-preview">
                    <div class="col-md-6 col-sm-12 mb-md-0 mb-5">
                        <img src="{{ property.picture.url }}" alt="Image" class="img-fluid tm-img-center-sm">
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <h2 class="tm-blue-text tm-margin-b-p">{{ property.name|title }}</h2>
                        <p class="tm-margin-b-p">{{ property.description|upper }}</p>
                        <p class="tm-blue-text tm-margin-b-s">City: {{ property.city.name|capfirst }}</p>
                        <p class="tm-blue-text tm-margin-b-s">Price: AR$ {{ property.daily_cost }}</p>
                    </div>
                </section>
			</div>
			<div class="col-12 col-md-10 offset-md-1 pt-3 pb-3" style="background-color: #f5f5f5;">
				<form action="/bookings/check_availability/" method="post">
					{% csrf_token %}
                    <div class="form-row align-items-center">
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">First Name</label>
                            <input type="text" name="first_name" class="form-control mb-2 mb-sm-0" placeholder="Jane" required>
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">Last Name</label>
                            <input type="text" name="last_name" class="form-control" placeholder="Doe" required>
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="inputEmail4">Email</label>
                            <input type="email" name="email" class="form-control" placeholder="name@mail.com" required>
                        </div>
                    </div>
					<div class="form-row align-items-center">
						<div class="form-group col-sm-3">
                            <label for="inputEmail4">Check-in</label>
							<input type="date" name="start_date" class="form-control mb-2 mb-sm-0" required>
						</div>
						<div class="form-group col-sm-3">
                            <label for="inputEmail4">Check-out</label>
							<input type="date" name="end_date" class="form-control" required>
						</div>
						<input type="hidden" name="property_id" value="{{ property.id }}">
					</div>
                    <div class="form-group float-right">
                        <button type="submit" class="btn btn-warning">Reserve</button>
                    </div>
				</form>
			</div>
		</div>
	</div>

	{% include "./../base/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}

src/iquilar/bookings/templates/bookings/hotel-list.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../base/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12">
				{% if properties %}
					{% for property in properties %}
						<div class="media mt-3 mb-3 animated fadeIn">
							<img class="mr-3" src="{{ property.picture.url }}" width="250" height="150"
							     alt="Generic placeholder image">
							<div class="media-body">
								<div class="container">
									<div class="row">
										<div class="col-6">
											<h5 class="mt-0">{{ property.name|title }}</h5>
										</div>
										<div class="col-6">
											<div class="float-right">
												{% url 'bookings:hotel_details' property.id as hotel_details %}
												<a class="btn btn-outline-success" href="{{ hotel_details }}"
												   role="button">Reserve</a>
											</div>
										</div>
										<div class="col-12">
											<p class="small text-muted">{{ property.city.name|capfirst }}</p>
										</div>
										<div class="col-12">
											<p class="text-muted">{{ property.description|upper }}</p>
										</div>
										<div class="col-12">
											<div class="float-right">
												<h4>AR$&nbsp;{{ property.daily_cost }}</h4>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<hr>
					{% endfor %}
					<h6 class="text-center">No more results</h6>
				{% else %}
					<h6 class="text-center mt-3">Couldn't find properties, try again later.</h6>
				{% endif %}
			</div>
		</div>
	</div>

	{% include "./../base/footer.html" %}

{% endblock %}

src/iquilar/bookings/templates/bookings/hotel-search-results.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../base/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12">
				{% if properties %}
					{% for property in properties %}
						<div class="media mt-3 mb-3 animated fadeIn">
							<img class="mr-3" src="{{ property.picture.url }}" width="250" height="150"
							     alt="Generic placeholder image">
							<div class="media-body">
								<div class="container">
									<div class="row">
										<div class="col-6">
											<h5 class="mt-0">{{ property.name|title }}</h5>
										</div>
										<div class="col-6">
											<div class="float-right">
												{% url 'bookings:hotel_details' property.id as hotel_details %}
												<a class="btn btn-outline-success" href="{{ hotel_details }}"
												   role="button">Reserve</a>
											</div>
										</div>
										<div class="col-12">
											<p class="small text-muted">{{ property.city.name|capfirst }}</p>
										</div>
										<div class="col-12">
											<p class="text-muted">{{ property.description|upper }}</p>
										</div>
										<div class="col-12">
											<div class="float-right">
												<h4>AR$&nbsp;{{ property.daily_cost }}</h4>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<hr>
					{% endfor %}
					<h6 class="text-center">No more results</h6>
				{% else %}
					<h6 class="text-center mt-3">Couldn't find properties, try again later.</h6>
				{% endif %}
			</div>
		</div>
	</div>

	{% include "./../base/footer.html" %}

{% endblock %}

src/iquilar/bookings/templates/bookings/index.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Home{% endblock %}

{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"/>
{% endblock %}

{% block content %}

	{% include "./../base/navbar.html" %}

	<div class="container-fluid bg-index-picture">
		<div class="row">
			<div class="col-12 col-lg-8 offset-lg-2">
				<section class="jumbotron text-left text-white" style="margin-top: 32px; background: rgba(0,0,0,0.56);">
					<h1 class="display-6">Search Hotels</h1>
					<form action="/bookings/search/" method="post">
						{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-6">
								<label class="col-form-label" for="goToSelectInput">Go to</label>
								<select class="form-control form-control-sm" name="city" id="goToSelectInput">
									<option value="{{ None }}">- - - - -</option>
									{% for city in cities %}
										<option value="{{ city.id }}">{{ city.picture.url }}</option>
									{% endfor %}
								</select>
							</div>
							<div class="form-group col-3">
								<label class="col-form-label" for="PassengersSelectInput">Passengers</label>
								<select class="form-control form-control-sm" name="pax" id="PassengersSelectInput">
									<option value="{{ None }}">- - - - -</option>
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
								</select>
							</div>							
							<div class="form-group col-3">
								<label class="col-form-label" for="maxPriceInput">Max. Price</label>
								<div class="input-group input-group-sm">
									<div class="input-group-addon">$</div>
									<input type="text" class="form-control form-control-sm" name="max_price" id="maxPriceInput" placeholder="Price">
								</div>
							</div>
						</div>
						<div class="text-center">
							<button type="submit" class="btn btn-primary btn-lg">Search</button>
						</div>
					</form>
				</section>
			</div>
		</div>
	</div>
	<div class="container mx-auto">
		<div class="tm-main-content">
                <section class="tm-margin-b-l">
                    <header>
                        <h1 class="tm-main-title text-center m-5">Cities</h2>    
					</header>					
					<div class="container-fluid content-row">
                        <div class="row">
								{% for city in cities %}
										<figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
											<form id="my_form" action="/bookings/list/" method="post">
												{% csrf_token %}
												
												<div class="card h-100">
													<img class="card-img-top" src="{{ city.picture.url }}" width="250" height="150" alt="Card image cap">
													<div class="card-body text-center">
														<input class="form-control" type="hidden" name="city" value= "{{ city.id }}">
														<button type="submit" class="btn btn-info mt-2 center-block">{{ city.name }}</button>
													</div>
												</div>
											</form>
										</figure>
								{% endfor %}
							
						</div>   
					</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-12 bg-index-gray pt-3 pb-3">
				<div id="indexCarousel" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#indexCarousel" data-slide-to="0" class="active"></li>
						<li data-target="#indexCarousel" data-slide-to="1"></li>
						<li data-target="#indexCarousel" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img class="d-block w-100 img-fluid" width="800" height="400" src="{% static 'img/bg-index-carousel-1.jpg' %}" alt="First slide">
							<div class="carousel-caption d-none d-md-block">
								<h3>Travel</h3>
							</div>
						</div>
						<div class="carousel-item">
							<img class="d-block w-100 img-fluid" width="800" height="400" src="{% static 'img/bg-index-carousel-2.jpg' %}" alt="Second slide">
							<div class="carousel-caption d-none d-md-block">
								<h3>Discover</h3>
							</div>
						</div>
						<div class="carousel-item">
							<img class="d-block w-100 img-fluid" width="800" height="400" src="{% static 'img/bg-index-carousel-3.jpg' %}" alt="Third slide">
							<div class="carousel-caption d-none d-md-block">
								<h3>Enjoy</h3>
							</div>
						</div>
					</div>
					<a class="carousel-control-prev" href="#indexCarousel" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#indexCarousel" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>
	</div>

	{% include "./../base/footer.html" %}

{% endblock %}

src/iquilar/bookings/templates/bookings/itinerary.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

    {% include "./../base/navbar.html" %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="alert alert-light" role="alert">
                    <h6 class="text-center">Successful booking at iQuilar.</h6>
                </div>
            </div>
            <div class="col-12">
                <h6>Hi, this is the itinerary for <span class="text-info">{{ reservation.first_name }} {{ reservation.last_name }}</span>!:</h6>
                <br>
                <p class="font-weight-bold">Email: <span class="text-info">{{ reservation.email }}</span></p>
                <p class="font-weight-bold">Reservation made on: <span class="text-info">{{ reservation.reservation_date }}</span></p>
            </div>
        </div>
    </div>

    {% include "./../base/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}

src/iquilar/bookings/templates/bookings/no-availability.html
{% extends "./../base/base.html" %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

	{% include "./../base/navbar.html" %}

	<div class="container">
		<div class="row">
			<div class="col-12">
                <div class="alert alert-danger" role="alert">
                    <h6 class="text-center">Can't book now, try again later.</h6>
                </div>
                {% url 'bookings:index' as index %}
                <a type="button" href="{{ index }}" class="btn btn-secondary btn-lg btn-block">Go to search</a>
			</div>
		</div>
	</div>

	{% include "./../base/footer.html" %}

{% endblock %}

{% block scripts %}{% endblock %}